export const FETCH_ADS = 'FETCH_ADS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const AD_CREATE_SUCCESS = 'AD_CREATE_SUCCESS';
export const AD_CREATE_FAILURE = 'AD_CREATE_FAILURE';
export const SHOW_AD_DETAILS = 'SHOW_AD_DETAILS';
